# Generated by Django 5.2.6 on 2025-10-16 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('total_shares', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('band_low', models.DecimalField(decimal_places=2, max_digits=18)),
                ('band_high', models.DecimalField(decimal_places=2, max_digits=18)),
                ('last_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=4)),
                ('quantity', models.PositiveBigIntegerField()),
                ('quantity_filled', models.PositiveBigIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('PARTIALLY_FILLED', 'PARTIALLY_FILLED'), ('FILLED', 'FILLED'), ('CANCELED', 'CANCELED')], default='OPEN', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'company')},
            },
        ),
    ]
